/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperacaoRouteImport } from './routes/recuperacao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AtividadeRouteImport } from './routes/atividade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinosIndexRouteImport } from './routes/treinos.index'
import { Route as TreinosImportarRouteImport } from './routes/treinos.importar'
import { Route as ExercicioIdRouteImport } from './routes/exercicio.$id'

const RecuperacaoRoute = RecuperacaoRouteImport.update({
  id: '/recuperacao',
  path: '/recuperacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeRoute = AtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosIndexRoute = TreinosIndexRouteImport.update({
  id: '/treinos/',
  path: '/treinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosImportarRoute = TreinosImportarRouteImport.update({
  id: '/treinos/importar',
  path: '/treinos/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicioIdRoute = ExercicioIdRouteImport.update({
  id: '/exercicio/$id',
  path: '/exercicio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/calendario': typeof CalendarioRoute
  '/coach': typeof CoachRoute
  '/desempenho': typeof DesempenhoRoute
  '/evolucao': typeof EvolucaoRoute
  '/exercicios': typeof ExerciciosRoute
  '/insights': typeof InsightsRoute
  '/objetivos': typeof ObjetivosRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/exercicio/$id': typeof ExercicioIdRoute
  '/treinos/importar': typeof TreinosImportarRoute
  '/treinos/': typeof TreinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/calendario': typeof CalendarioRoute
  '/coach': typeof CoachRoute
  '/desempenho': typeof DesempenhoRoute
  '/evolucao': typeof EvolucaoRoute
  '/exercicios': typeof ExerciciosRoute
  '/insights': typeof InsightsRoute
  '/objetivos': typeof ObjetivosRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/exercicio/$id': typeof ExercicioIdRoute
  '/treinos/importar': typeof TreinosImportarRoute
  '/treinos': typeof TreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/calendario': typeof CalendarioRoute
  '/coach': typeof CoachRoute
  '/desempenho': typeof DesempenhoRoute
  '/evolucao': typeof EvolucaoRoute
  '/exercicios': typeof ExerciciosRoute
  '/insights': typeof InsightsRoute
  '/objetivos': typeof ObjetivosRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/exercicio/$id': typeof ExercicioIdRoute
  '/treinos/importar': typeof TreinosImportarRoute
  '/treinos/': typeof TreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividade'
    | '/calendario'
    | '/coach'
    | '/desempenho'
    | '/evolucao'
    | '/exercicios'
    | '/insights'
    | '/objetivos'
    | '/onboarding'
    | '/perfil'
    | '/recuperacao'
    | '/exercicio/$id'
    | '/treinos/importar'
    | '/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividade'
    | '/calendario'
    | '/coach'
    | '/desempenho'
    | '/evolucao'
    | '/exercicios'
    | '/insights'
    | '/objetivos'
    | '/onboarding'
    | '/perfil'
    | '/recuperacao'
    | '/exercicio/$id'
    | '/treinos/importar'
    | '/treinos'
  id:
    | '__root__'
    | '/'
    | '/atividade'
    | '/calendario'
    | '/coach'
    | '/desempenho'
    | '/evolucao'
    | '/exercicios'
    | '/insights'
    | '/objetivos'
    | '/onboarding'
    | '/perfil'
    | '/recuperacao'
    | '/exercicio/$id'
    | '/treinos/importar'
    | '/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadeRoute: typeof AtividadeRoute
  CalendarioRoute: typeof CalendarioRoute
  CoachRoute: typeof CoachRoute
  DesempenhoRoute: typeof DesempenhoRoute
  EvolucaoRoute: typeof EvolucaoRoute
  ExerciciosRoute: typeof ExerciciosRoute
  InsightsRoute: typeof InsightsRoute
  ObjetivosRoute: typeof ObjetivosRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  RecuperacaoRoute: typeof RecuperacaoRoute
  ExercicioIdRoute: typeof ExercicioIdRoute
  TreinosImportarRoute: typeof TreinosImportarRoute
  TreinosIndexRoute: typeof TreinosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperacao': {
      id: '/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof RecuperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade': {
      id: '/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AtividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/': {
      id: '/treinos/'
      path: '/treinos'
      fullPath: '/treinos/'
      preLoaderRoute: typeof TreinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/importar': {
      id: '/treinos/importar'
      path: '/treinos/importar'
      fullPath: '/treinos/importar'
      preLoaderRoute: typeof TreinosImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicio/$id': {
      id: '/exercicio/$id'
      path: '/exercicio/$id'
      fullPath: '/exercicio/$id'
      preLoaderRoute: typeof ExercicioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadeRoute: AtividadeRoute,
  CalendarioRoute: CalendarioRoute,
  CoachRoute: CoachRoute,
  DesempenhoRoute: DesempenhoRoute,
  EvolucaoRoute: EvolucaoRoute,
  ExerciciosRoute: ExerciciosRoute,
  InsightsRoute: InsightsRoute,
  ObjetivosRoute: ObjetivosRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  RecuperacaoRoute: RecuperacaoRoute,
  ExercicioIdRoute: ExercicioIdRoute,
  TreinosImportarRoute: TreinosImportarRoute,
  TreinosIndexRoute: TreinosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
